[platformio]
default_envs = waveshare_esp32s3_n16r8

[env:waveshare_esp32s3_n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
build_src_filter =
  +<*>
  -<aliyun_mqtt.cpp>
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DBOARD_HAS_PSRAM
lib_deps =
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^3.11.0
  knolleary/PubSubClient @ ^2.8

[env:waveshare_esp32s3_n16r8_remote_five]
extends = env:waveshare_esp32s3_n16r8
build_flags =
  ${env:waveshare_esp32s3_n16r8.build_flags}
